language: generic

install: false

addons:
  ssh_known_hosts:
  - 138.197.48.54

before_install:
- openssl aes-256-cbc -K $encrypted_0a36a92f17a8_key -iv $encrypted_0a36a92f17a8_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
- provider: script
  skip_cleanup: true
  script: rsync -v -r --delete-after --exclude '.git*' --exclude '*.enc' --exclude '.travis.*' $TRAVIS_BUILD_DIR/ deploy@138.197.48.54:/var/www/www-sequinsandscrums-org
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: rsync -v -r --delete-after --exclude '.git*' --exclude '*.enc' --exclude '.travis.*' $TRAVIS_BUILD_DIR/ deploy@138.197.48.54:/var/www/test-sequinsandscrums-org
  on:
    branch: develop
